//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task4.DM
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleSet
    {
        public int Id { get; set; }
        public string Data { get; set; }
        public int Manager_Id { get; set; }
        public int Product_Id { get; set; }
        public int Client_Id { get; set; }
    
        public virtual ClientSet ClientSet { get; set; }
        public virtual ManagerSet ManagerSet { get; set; }
        public virtual ProductSet ProductSet { get; set; }
    }
}
